### ISSUE TITLE
About 1.0? release

### ISSUE THREAD

**Issue by kenhys** [kbingham/xhk#7]
I want to make a package available in debian, but it seems that there is no release and no tags in the repository.
 
Could you make a new release and upload an archive file(tar.gz or tar.xz or something)?

**Comment by kbingham** [comment]
Hi @kenhys 

I can do - sure. I haven't really used this code in a long time. Have you used it and found it useful?
It's worth noting that once systems go to wayland - this won't work anymore.

**Comment by kenhys** [comment]
Hi @kbingham 

I began to use it recently and found it useful, sure.
It is valuable if package is available by default even though system going to switch wayland until then.

**Comment by kenhys** [comment]
@kbingham when new release archive will be available? (I'm not intended to rush you so, I'm just curious about it)

**Comment by kenhys** [comment]
ping @kbingham ?

**Comment by kbingham** [comment]
Having updated the version strings and re-run the man page generator - I've added a tag. This was automatically picked up by github and has created links for zip/tgz files I believe.

Feel free to send pull requests if there is anything else you'd like to fix up or change.

Cheers
Kieran
