### ISSUE TITLE
doc/xhk.1  is a bit outdated

### ISSUE THREAD

**Issue by kenhys** [kbingham/xhk#8]
# Summary

The description of command line argument seems a bit outdated.

# Actual

Debug option is described as `-v`.
```
\fB\-v\fR increase verbosity levels
```

# Expected

Debug option should be described as `-d`.

```
\fB\-d\fR increase debug verbosity levels
```

**Comment by kbingham** [comment]
I've updated the man file by running help2man xhk -o doc/xhk.1
I hope this fixes the issue for you.
Let me know if there are any problems.
