### ISSUE TITLE
The man page is corrupted

### ISSUE THREAD

**Issue by kenhys** [kbingham/xhk#9]
# Background

I am working of packaging xhk into debian, and I got a review feedback about the man page.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917629#14

# Problem

Generated doc/xhk.1 contains corrupted description section.

# Actual

It seems that unexpected  escape sequence and duplicated description are contained.

```
 5 .SH DESCRIPTION
  6 \fB\-\-\fR HalfKey Xorg Driver Utility 1.0 \fB\-\-\fR
  7 ^[[1m    usage:
  8 .IP
  9 \fB\-m\fR mirror mode \- all keys reversed
 10 \fB\-d\fR increase debug verbosity levels
 11 \fB\-h\fR this help
 12 .PP
 13 ^[[0m
 14 .PP
 15 \fB\-\-\fR HalfKey Xorg Driver Utility 1.0 \fB\-\-\fR
 16 ^[[1m    usage:
 17 .IP
 18 \fB\-m\fR mirror mode \- all keys reversed
 19 \fB\-d\fR increase debug verbosity levels
 20 \fB\-h\fR this help
 21 .PP
 22 ^[[0m
```

# Expected

1. name section contains approprate one. It still contains no informative template.

```
 3 .SH NAME
  4 xhk \- manual page for xhk 
```

2. no corrupted escape sequence. It may be come from hardcoded escape in usage function call.

3. drop "see also" section because there is no info file for xhk.

Above issue is solved by usage of help2man at some extent, I mean:

```
help2man -o xhk.1 --no-info --name "A half keyboard mirroring implementation to help one handed typist" xhk
```

It solves 1. and 3, but it is not enough for 2.

To solve 2. completely, we need write man file template manually (not all).
Here is a example:

```
% cat template
[=NAME]

xhk \- HalfKey Xorg Driver Utility 1.0

[=SYNOPSIS]

xhk [OPTION]

[=DESCRIPTION]
.PP
xhk is a half keyboard mirroring implementation to help one handed typist.

.TP
.B
\-m
mirror mode - all keys reversed
.TP
.B
\-d
increase debug verbosity levels
.TP
.B
\-h
this help
.PP
Running xhk detaches the keyboard, and intercepts all input; processing it for
space bar pushes as it goes. The space bar acts as a modifier if it is held at
the same time as a standard letter. Modifying acts to mirror the input such
that key presses are mirrored down the middle of the home row.
Pressing space, and then releasing will still provide a single space character
```

Then convert it as like this:
```
help2man -o xhk.1 --include template --no-info xhk
```

The problem of above way is: It takes maintainance cost. (even though there is no need to write whole man file content) and not cool.

Are threre any good idea to improve this situation?

**Comment by kbingham** [comment]
Hrm. I have no idea why it represents the text twice, and the formatting certainly doesn't work very well.
I suspect just going with your manual template will be the best option for now.

The maintenance overhead is likely to be low currently as development is low - so I don't expect a lot of churn until there are more people using this.
At which point we can revisit if necessary.

Could you submit a patch to fix things up as you need them please?
It might be worth just dropping the whole help2man thing altogther and just having a hand written file for now too.

**Comment by kenhys** [comment]
Instead of help2man, I used pandoc as a alternative converter #10 .
It seems that it is easy to maintain content.

**Comment by kbingham** [comment]
I agree... it looks easier to maintain the content. I've merged your pull-request.

**Comment by kbingham** [comment]
https://github.com/kbingham/xhk/releases/tag/xhk-v1.1 tagged to help with your packaging work.
